// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: protocol/protobuf/loghub/loghub.proto

package loghub

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogHubService_Write_FullMethodName          = "/infra.loghub.v1.LogHubService/Write"
	LogHubService_Bulk_FullMethodName           = "/infra.loghub.v1.LogHubService/Bulk"
	LogHubService_ListStreams_FullMethodName    = "/infra.loghub.v1.LogHubService/ListStreams"
	LogHubService_DescribeStream_FullMethodName = "/infra.loghub.v1.LogHubService/DescribeStream"
)

// LogHubServiceClient is the client API for LogHubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LogHubService - public log hub
type LogHubServiceClient interface {
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	Bulk(ctx context.Context, in *BulkRequest, opts ...grpc.CallOption) (*BulkResponse, error)
	ListStreams(ctx context.Context, in *ListStreamsRequest, opts ...grpc.CallOption) (*ListStreamsResponse, error)
	DescribeStream(ctx context.Context, in *DescribeStreamRequest, opts ...grpc.CallOption) (*DescribeStreamResponse, error)
}

type logHubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogHubServiceClient(cc grpc.ClientConnInterface) LogHubServiceClient {
	return &logHubServiceClient{cc}
}

func (c *logHubServiceClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, LogHubService_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logHubServiceClient) Bulk(ctx context.Context, in *BulkRequest, opts ...grpc.CallOption) (*BulkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkResponse)
	err := c.cc.Invoke(ctx, LogHubService_Bulk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logHubServiceClient) ListStreams(ctx context.Context, in *ListStreamsRequest, opts ...grpc.CallOption) (*ListStreamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStreamsResponse)
	err := c.cc.Invoke(ctx, LogHubService_ListStreams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logHubServiceClient) DescribeStream(ctx context.Context, in *DescribeStreamRequest, opts ...grpc.CallOption) (*DescribeStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeStreamResponse)
	err := c.cc.Invoke(ctx, LogHubService_DescribeStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogHubServiceServer is the server API for LogHubService service.
// All implementations must embed UnimplementedLogHubServiceServer
// for forward compatibility.
//
// LogHubService - public log hub
type LogHubServiceServer interface {
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	Bulk(context.Context, *BulkRequest) (*BulkResponse, error)
	ListStreams(context.Context, *ListStreamsRequest) (*ListStreamsResponse, error)
	DescribeStream(context.Context, *DescribeStreamRequest) (*DescribeStreamResponse, error)
	mustEmbedUnimplementedLogHubServiceServer()
}

// UnimplementedLogHubServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogHubServiceServer struct{}

func (UnimplementedLogHubServiceServer) Write(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedLogHubServiceServer) Bulk(context.Context, *BulkRequest) (*BulkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Bulk not implemented")
}
func (UnimplementedLogHubServiceServer) ListStreams(context.Context, *ListStreamsRequest) (*ListStreamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStreams not implemented")
}
func (UnimplementedLogHubServiceServer) DescribeStream(context.Context, *DescribeStreamRequest) (*DescribeStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeStream not implemented")
}
func (UnimplementedLogHubServiceServer) mustEmbedUnimplementedLogHubServiceServer() {}
func (UnimplementedLogHubServiceServer) testEmbeddedByValue()                       {}

// UnsafeLogHubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogHubServiceServer will
// result in compilation errors.
type UnsafeLogHubServiceServer interface {
	mustEmbedUnimplementedLogHubServiceServer()
}

func RegisterLogHubServiceServer(s grpc.ServiceRegistrar, srv LogHubServiceServer) {
	// If the following call panics, it indicates UnimplementedLogHubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogHubService_ServiceDesc, srv)
}

func _LogHubService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogHubServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogHubService_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogHubServiceServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogHubService_Bulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogHubServiceServer).Bulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogHubService_Bulk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogHubServiceServer).Bulk(ctx, req.(*BulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogHubService_ListStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogHubServiceServer).ListStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogHubService_ListStreams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogHubServiceServer).ListStreams(ctx, req.(*ListStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogHubService_DescribeStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogHubServiceServer).DescribeStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogHubService_DescribeStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogHubServiceServer).DescribeStream(ctx, req.(*DescribeStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogHubService_ServiceDesc is the grpc.ServiceDesc for LogHubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogHubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infra.loghub.v1.LogHubService",
	HandlerType: (*LogHubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _LogHubService_Write_Handler,
		},
		{
			MethodName: "Bulk",
			Handler:    _LogHubService_Bulk_Handler,
		},
		{
			MethodName: "ListStreams",
			Handler:    _LogHubService_ListStreams_Handler,
		},
		{
			MethodName: "DescribeStream",
			Handler:    _LogHubService_DescribeStream_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol/protobuf/loghub/loghub.proto",
}
