// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: protocol/protobuf/loghub/loghub.proto

package loghub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogEvent - simplified OpenTelemetry Logs model
type LogEvent struct {
	state                     protoimpl.MessageState     `protogen:"open.v1"`
	Stream                    string                     `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	TimestampUnixNano         int64                      `protobuf:"varint,2,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	ObservedTimestampUnixNano int64                      `protobuf:"varint,3,opt,name=observed_timestamp_unix_nano,json=observedTimestampUnixNano,proto3" json:"observed_timestamp_unix_nano,omitempty"`
	SeverityText              string                     `protobuf:"bytes,4,opt,name=severity_text,json=severityText,proto3" json:"severity_text,omitempty"`
	SeverityNumber            int32                      `protobuf:"varint,5,opt,name=severity_number,json=severityNumber,proto3" json:"severity_number,omitempty"`
	TraceId                   string                     `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId                    string                     `protobuf:"bytes,7,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Attributes                map[string]*AttributeValue `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body                      []byte                     `protobuf:"bytes,9,opt,name=body,proto3" json:"body,omitempty"`
	Resource                  map[string]*AttributeValue `protobuf:"bytes,10,rep,name=resource,proto3" json:"resource,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_protocol_protobuf_loghub_loghub_proto_rawDescGZIP(), []int{0}
}

func (x *LogEvent) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogEvent) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *LogEvent) GetObservedTimestampUnixNano() int64 {
	if x != nil {
		return x.ObservedTimestampUnixNano
	}
	return 0
}

func (x *LogEvent) GetSeverityText() string {
	if x != nil {
		return x.SeverityText
	}
	return ""
}

func (x *LogEvent) GetSeverityNumber() int32 {
	if x != nil {
		return x.SeverityNumber
	}
	return 0
}

func (x *LogEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LogEvent) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *LogEvent) GetAttributes() map[string]*AttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *LogEvent) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *LogEvent) GetResource() map[string]*AttributeValue {
	if x != nil {
		return x.Resource
	}
	return nil
}

type AttributeValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*AttributeValue_StringValue
	//	*AttributeValue_IntValue
	//	*AttributeValue_DoubleValue
	//	*AttributeValue_BoolValue
	//	*AttributeValue_ArrayValue
	Value         isAttributeValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeValue) Reset() {
	*x = AttributeValue{}
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValue) ProtoMessage() {}

func (x *AttributeValue) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValue.ProtoReflect.Descriptor instead.
func (*AttributeValue) Descriptor() ([]byte, []int) {
	return file_protocol_protobuf_loghub_loghub_proto_rawDescGZIP(), []int{1}
}

func (x *AttributeValue) GetValue() isAttributeValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AttributeValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *AttributeValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *AttributeValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *AttributeValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *AttributeValue) GetArrayValue() *AttributeArray {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_ArrayValue); ok {
			return x.ArrayValue
		}
	}
	return nil
}

type isAttributeValue_Value interface {
	isAttributeValue_Value()
}

type AttributeValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type AttributeValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type AttributeValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type AttributeValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type AttributeValue_ArrayValue struct {
	ArrayValue *AttributeArray `protobuf:"bytes,5,opt,name=array_value,json=arrayValue,proto3,oneof"`
}

func (*AttributeValue_StringValue) isAttributeValue_Value() {}

func (*AttributeValue_IntValue) isAttributeValue_Value() {}

func (*AttributeValue_DoubleValue) isAttributeValue_Value() {}

func (*AttributeValue_BoolValue) isAttributeValue_Value() {}

func (*AttributeValue_ArrayValue) isAttributeValue_Value() {}

type AttributeArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*AttributeValue      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeArray) Reset() {
	*x = AttributeArray{}
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeArray) ProtoMessage() {}

func (x *AttributeArray) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeArray.ProtoReflect.Descriptor instead.
func (*AttributeArray) Descriptor() ([]byte, []int) {
	return file_protocol_protobuf_loghub_loghub_proto_rawDescGZIP(), []int{2}
}

func (x *AttributeArray) GetValues() []*AttributeValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *LogEvent              `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protobuf_loghub_loghub_proto_rawDescGZIP(), []int{3}
}

func (x *WriteRequest) GetEvent() *LogEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Backend       string                 `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protobuf_loghub_loghub_proto_rawDescGZIP(), []int{4}
}

func (x *WriteResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *WriteResponse) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *WriteResponse) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

type BulkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*LogEvent            `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkRequest) Reset() {
	*x = BulkRequest{}
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkRequest) ProtoMessage() {}

func (x *BulkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkRequest.ProtoReflect.Descriptor instead.
func (*BulkRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protobuf_loghub_loghub_proto_rawDescGZIP(), []int{5}
}

func (x *BulkRequest) GetEvents() []*LogEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type BulkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BulkItemResult      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	SuccessCount  int32                  `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailureCount  int32                  `protobuf:"varint,3,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	TookMs        int64                  `protobuf:"varint,4,opt,name=took_ms,json=tookMs,proto3" json:"took_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkResponse) Reset() {
	*x = BulkResponse{}
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkResponse) ProtoMessage() {}

func (x *BulkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkResponse.ProtoReflect.Descriptor instead.
func (*BulkResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protobuf_loghub_loghub_proto_rawDescGZIP(), []int{6}
}

func (x *BulkResponse) GetItems() []*BulkItemResult {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BulkResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BulkResponse) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *BulkResponse) GetTookMs() int64 {
	if x != nil {
		return x.TookMs
	}
	return 0
}

type BulkItemResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Stream        string                 `protobuf:"bytes,3,opt,name=stream,proto3" json:"stream,omitempty"`
	Error         *ItemError             `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkItemResult) Reset() {
	*x = BulkItemResult{}
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkItemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkItemResult) ProtoMessage() {}

func (x *BulkItemResult) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkItemResult.ProtoReflect.Descriptor instead.
func (*BulkItemResult) Descriptor() ([]byte, []int) {
	return file_protocol_protobuf_loghub_loghub_proto_rawDescGZIP(), []int{7}
}

func (x *BulkItemResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BulkItemResult) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *BulkItemResult) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *BulkItemResult) GetError() *ItemError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListStreamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStreamsRequest) Reset() {
	*x = ListStreamsRequest{}
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsRequest) ProtoMessage() {}

func (x *ListStreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsRequest.ProtoReflect.Descriptor instead.
func (*ListStreamsRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protobuf_loghub_loghub_proto_rawDescGZIP(), []int{8}
}

type ListStreamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []*StreamSummary       `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStreamsResponse) Reset() {
	*x = ListStreamsResponse{}
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsResponse) ProtoMessage() {}

func (x *ListStreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsResponse.ProtoReflect.Descriptor instead.
func (*ListStreamsResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protobuf_loghub_loghub_proto_rawDescGZIP(), []int{9}
}

func (x *ListStreamsResponse) GetStreams() []*StreamSummary {
	if x != nil {
		return x.Streams
	}
	return nil
}

type StreamSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Backend        string                 `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	BodyFormat     string                 `protobuf:"bytes,3,opt,name=body_format,json=bodyFormat,proto3" json:"body_format,omitempty"`
	AttributeCount int32                  `protobuf:"varint,4,opt,name=attribute_count,json=attributeCount,proto3" json:"attribute_count,omitempty"`
	AllowedCallers []string               `protobuf:"bytes,5,rep,name=allowed_callers,json=allowedCallers,proto3" json:"allowed_callers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamSummary) Reset() {
	*x = StreamSummary{}
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSummary) ProtoMessage() {}

func (x *StreamSummary) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSummary.ProtoReflect.Descriptor instead.
func (*StreamSummary) Descriptor() ([]byte, []int) {
	return file_protocol_protobuf_loghub_loghub_proto_rawDescGZIP(), []int{10}
}

func (x *StreamSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamSummary) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *StreamSummary) GetBodyFormat() string {
	if x != nil {
		return x.BodyFormat
	}
	return ""
}

func (x *StreamSummary) GetAttributeCount() int32 {
	if x != nil {
		return x.AttributeCount
	}
	return 0
}

func (x *StreamSummary) GetAllowedCallers() []string {
	if x != nil {
		return x.AllowedCallers
	}
	return nil
}

type DescribeStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeStreamRequest) Reset() {
	*x = DescribeStreamRequest{}
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeStreamRequest) ProtoMessage() {}

func (x *DescribeStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeStreamRequest.ProtoReflect.Descriptor instead.
func (*DescribeStreamRequest) Descriptor() ([]byte, []int) {
	return file_protocol_protobuf_loghub_loghub_proto_rawDescGZIP(), []int{11}
}

func (x *DescribeStreamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DescribeStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *StreamConfig          `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeStreamResponse) Reset() {
	*x = DescribeStreamResponse{}
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeStreamResponse) ProtoMessage() {}

func (x *DescribeStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeStreamResponse.ProtoReflect.Descriptor instead.
func (*DescribeStreamResponse) Descriptor() ([]byte, []int) {
	return file_protocol_protobuf_loghub_loghub_proto_rawDescGZIP(), []int{12}
}

func (x *DescribeStreamResponse) GetStream() *StreamConfig {
	if x != nil {
		return x.Stream
	}
	return nil
}

type StreamConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Backend        string                 `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	BodyFormat     string                 `protobuf:"bytes,3,opt,name=body_format,json=bodyFormat,proto3" json:"body_format,omitempty"`
	Attributes     []*AttributeSchema     `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty"`
	AllowedCallers []string               `protobuf:"bytes,5,rep,name=allowed_callers,json=allowedCallers,proto3" json:"allowed_callers,omitempty"`
	Retention      string                 `protobuf:"bytes,6,opt,name=retention,proto3" json:"retention,omitempty"`
	Es             *ESBackendConfig       `protobuf:"bytes,10,opt,name=es,proto3" json:"es,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamConfig) Reset() {
	*x = StreamConfig{}
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamConfig) ProtoMessage() {}

func (x *StreamConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamConfig.ProtoReflect.Descriptor instead.
func (*StreamConfig) Descriptor() ([]byte, []int) {
	return file_protocol_protobuf_loghub_loghub_proto_rawDescGZIP(), []int{13}
}

func (x *StreamConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamConfig) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *StreamConfig) GetBodyFormat() string {
	if x != nil {
		return x.BodyFormat
	}
	return ""
}

func (x *StreamConfig) GetAttributes() []*AttributeSchema {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *StreamConfig) GetAllowedCallers() []string {
	if x != nil {
		return x.AllowedCallers
	}
	return nil
}

func (x *StreamConfig) GetRetention() string {
	if x != nil {
		return x.Retention
	}
	return ""
}

func (x *StreamConfig) GetEs() *ESBackendConfig {
	if x != nil {
		return x.Es
	}
	return nil
}

type AttributeSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// keyword / text / integer / long / double / boolean / date / ip
	Type          string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeSchema) Reset() {
	*x = AttributeSchema{}
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeSchema) ProtoMessage() {}

func (x *AttributeSchema) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeSchema.ProtoReflect.Descriptor instead.
func (*AttributeSchema) Descriptor() ([]byte, []int) {
	return file_protocol_protobuf_loghub_loghub_proto_rawDescGZIP(), []int{14}
}

func (x *AttributeSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttributeSchema) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AttributeSchema) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type ESBackendConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexPattern  string                 `protobuf:"bytes,1,opt,name=index_pattern,json=indexPattern,proto3" json:"index_pattern,omitempty"`
	TemplateName  string                 `protobuf:"bytes,2,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	Cluster       string                 `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ESBackendConfig) Reset() {
	*x = ESBackendConfig{}
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ESBackendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESBackendConfig) ProtoMessage() {}

func (x *ESBackendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESBackendConfig.ProtoReflect.Descriptor instead.
func (*ESBackendConfig) Descriptor() ([]byte, []int) {
	return file_protocol_protobuf_loghub_loghub_proto_rawDescGZIP(), []int{15}
}

func (x *ESBackendConfig) GetIndexPattern() string {
	if x != nil {
		return x.IndexPattern
	}
	return ""
}

func (x *ESBackendConfig) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *ESBackendConfig) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

// Item error - reused from old proto, kept for compat
type ItemError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Field         string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	EsErrorType   string                 `protobuf:"bytes,4,opt,name=es_error_type,json=esErrorType,proto3" json:"es_error_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemError) Reset() {
	*x = ItemError{}
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemError) ProtoMessage() {}

func (x *ItemError) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_protobuf_loghub_loghub_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemError.ProtoReflect.Descriptor instead.
func (*ItemError) Descriptor() ([]byte, []int) {
	return file_protocol_protobuf_loghub_loghub_proto_rawDescGZIP(), []int{16}
}

func (x *ItemError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ItemError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ItemError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ItemError) GetEsErrorType() string {
	if x != nil {
		return x.EsErrorType
	}
	return ""
}

var File_protocol_protobuf_loghub_loghub_proto protoreflect.FileDescriptor

const file_protocol_protobuf_loghub_loghub_proto_rawDesc = "" +
	"\n" +
	"%protocol/protobuf/loghub/loghub.proto\x12\x0finfra.loghub.v1\"\xf7\x04\n" +
	"\bLogEvent\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12.\n" +
	"\x13timestamp_unix_nano\x18\x02 \x01(\x03R\x11timestampUnixNano\x12?\n" +
	"\x1cobserved_timestamp_unix_nano\x18\x03 \x01(\x03R\x19observedTimestampUnixNano\x12#\n" +
	"\rseverity_text\x18\x04 \x01(\tR\fseverityText\x12'\n" +
	"\x0fseverity_number\x18\x05 \x01(\x05R\x0eseverityNumber\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\a \x01(\tR\x06spanId\x12I\n" +
	"\n" +
	"attributes\x18\b \x03(\v2).infra.loghub.v1.LogEvent.AttributesEntryR\n" +
	"attributes\x12\x12\n" +
	"\x04body\x18\t \x01(\fR\x04body\x12C\n" +
	"\bresource\x18\n" +
	" \x03(\v2'.infra.loghub.v1.LogEvent.ResourceEntryR\bresource\x1a^\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.infra.loghub.v1.AttributeValueR\x05value:\x028\x01\x1a\\\n" +
	"\rResourceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.infra.loghub.v1.AttributeValueR\x05value:\x028\x01\"\xe7\x01\n" +
	"\x0eAttributeValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12B\n" +
	"\varray_value\x18\x05 \x01(\v2\x1f.infra.loghub.v1.AttributeArrayH\x00R\n" +
	"arrayValueB\a\n" +
	"\x05value\"I\n" +
	"\x0eAttributeArray\x127\n" +
	"\x06values\x18\x01 \x03(\v2\x1f.infra.loghub.v1.AttributeValueR\x06values\"?\n" +
	"\fWriteRequest\x12/\n" +
	"\x05event\x18\x01 \x01(\v2\x19.infra.loghub.v1.LogEventR\x05event\"\\\n" +
	"\rWriteResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x18\n" +
	"\abackend\x18\x03 \x01(\tR\abackend\"@\n" +
	"\vBulkRequest\x121\n" +
	"\x06events\x18\x01 \x03(\v2\x19.infra.loghub.v1.LogEventR\x06events\"\xa8\x01\n" +
	"\fBulkResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.infra.loghub.v1.BulkItemResultR\x05items\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x05R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x03 \x01(\x05R\ffailureCount\x12\x17\n" +
	"\atook_ms\x18\x04 \x01(\x03R\x06tookMs\"\x8f\x01\n" +
	"\x0eBulkItemResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\tR\x06stream\x120\n" +
	"\x05error\x18\n" +
	" \x01(\v2\x1a.infra.loghub.v1.ItemErrorR\x05error\"\x14\n" +
	"\x12ListStreamsRequest\"O\n" +
	"\x13ListStreamsResponse\x128\n" +
	"\astreams\x18\x01 \x03(\v2\x1e.infra.loghub.v1.StreamSummaryR\astreams\"\xb0\x01\n" +
	"\rStreamSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\x12\x1f\n" +
	"\vbody_format\x18\x03 \x01(\tR\n" +
	"bodyFormat\x12'\n" +
	"\x0fattribute_count\x18\x04 \x01(\x05R\x0eattributeCount\x12'\n" +
	"\x0fallowed_callers\x18\x05 \x03(\tR\x0eallowedCallers\"+\n" +
	"\x15DescribeStreamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"O\n" +
	"\x16DescribeStreamResponse\x125\n" +
	"\x06stream\x18\x01 \x01(\v2\x1d.infra.loghub.v1.StreamConfigR\x06stream\"\x98\x02\n" +
	"\fStreamConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\x12\x1f\n" +
	"\vbody_format\x18\x03 \x01(\tR\n" +
	"bodyFormat\x12@\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2 .infra.loghub.v1.AttributeSchemaR\n" +
	"attributes\x12'\n" +
	"\x0fallowed_callers\x18\x05 \x03(\tR\x0eallowedCallers\x12\x1c\n" +
	"\tretention\x18\x06 \x01(\tR\tretention\x120\n" +
	"\x02es\x18\n" +
	" \x01(\v2 .infra.loghub.v1.ESBackendConfigR\x02es\"U\n" +
	"\x0fAttributeSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\"u\n" +
	"\x0fESBackendConfig\x12#\n" +
	"\rindex_pattern\x18\x01 \x01(\tR\findexPattern\x12#\n" +
	"\rtemplate_name\x18\x02 \x01(\tR\ftemplateName\x12\x18\n" +
	"\acluster\x18\x03 \x01(\tR\acluster\"s\n" +
	"\tItemError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field\x12\"\n" +
	"\res_error_type\x18\x04 \x01(\tR\vesErrorType2\xd9\x02\n" +
	"\rLogHubService\x12F\n" +
	"\x05Write\x12\x1d.infra.loghub.v1.WriteRequest\x1a\x1e.infra.loghub.v1.WriteResponse\x12C\n" +
	"\x04Bulk\x12\x1c.infra.loghub.v1.BulkRequest\x1a\x1d.infra.loghub.v1.BulkResponse\x12X\n" +
	"\vListStreams\x12#.infra.loghub.v1.ListStreamsRequest\x1a$.infra.loghub.v1.ListStreamsResponse\x12a\n" +
	"\x0eDescribeStream\x12&.infra.loghub.v1.DescribeStreamRequest\x1a'.infra.loghub.v1.DescribeStreamResponseBOZMgitlab.xaminim.com/infra/system_group/log-hub/protocol/protobuf/loghub;loghubb\x06proto3"

var (
	file_protocol_protobuf_loghub_loghub_proto_rawDescOnce sync.Once
	file_protocol_protobuf_loghub_loghub_proto_rawDescData []byte
)

func file_protocol_protobuf_loghub_loghub_proto_rawDescGZIP() []byte {
	file_protocol_protobuf_loghub_loghub_proto_rawDescOnce.Do(func() {
		file_protocol_protobuf_loghub_loghub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_protobuf_loghub_loghub_proto_rawDesc), len(file_protocol_protobuf_loghub_loghub_proto_rawDesc)))
	})
	return file_protocol_protobuf_loghub_loghub_proto_rawDescData
}

var file_protocol_protobuf_loghub_loghub_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_protocol_protobuf_loghub_loghub_proto_goTypes = []any{
	(*LogEvent)(nil),               // 0: infra.loghub.v1.LogEvent
	(*AttributeValue)(nil),         // 1: infra.loghub.v1.AttributeValue
	(*AttributeArray)(nil),         // 2: infra.loghub.v1.AttributeArray
	(*WriteRequest)(nil),           // 3: infra.loghub.v1.WriteRequest
	(*WriteResponse)(nil),          // 4: infra.loghub.v1.WriteResponse
	(*BulkRequest)(nil),            // 5: infra.loghub.v1.BulkRequest
	(*BulkResponse)(nil),           // 6: infra.loghub.v1.BulkResponse
	(*BulkItemResult)(nil),         // 7: infra.loghub.v1.BulkItemResult
	(*ListStreamsRequest)(nil),     // 8: infra.loghub.v1.ListStreamsRequest
	(*ListStreamsResponse)(nil),    // 9: infra.loghub.v1.ListStreamsResponse
	(*StreamSummary)(nil),          // 10: infra.loghub.v1.StreamSummary
	(*DescribeStreamRequest)(nil),  // 11: infra.loghub.v1.DescribeStreamRequest
	(*DescribeStreamResponse)(nil), // 12: infra.loghub.v1.DescribeStreamResponse
	(*StreamConfig)(nil),           // 13: infra.loghub.v1.StreamConfig
	(*AttributeSchema)(nil),        // 14: infra.loghub.v1.AttributeSchema
	(*ESBackendConfig)(nil),        // 15: infra.loghub.v1.ESBackendConfig
	(*ItemError)(nil),              // 16: infra.loghub.v1.ItemError
	nil,                            // 17: infra.loghub.v1.LogEvent.AttributesEntry
	nil,                            // 18: infra.loghub.v1.LogEvent.ResourceEntry
}
var file_protocol_protobuf_loghub_loghub_proto_depIdxs = []int32{
	17, // 0: infra.loghub.v1.LogEvent.attributes:type_name -> infra.loghub.v1.LogEvent.AttributesEntry
	18, // 1: infra.loghub.v1.LogEvent.resource:type_name -> infra.loghub.v1.LogEvent.ResourceEntry
	2,  // 2: infra.loghub.v1.AttributeValue.array_value:type_name -> infra.loghub.v1.AttributeArray
	1,  // 3: infra.loghub.v1.AttributeArray.values:type_name -> infra.loghub.v1.AttributeValue
	0,  // 4: infra.loghub.v1.WriteRequest.event:type_name -> infra.loghub.v1.LogEvent
	0,  // 5: infra.loghub.v1.BulkRequest.events:type_name -> infra.loghub.v1.LogEvent
	7,  // 6: infra.loghub.v1.BulkResponse.items:type_name -> infra.loghub.v1.BulkItemResult
	16, // 7: infra.loghub.v1.BulkItemResult.error:type_name -> infra.loghub.v1.ItemError
	10, // 8: infra.loghub.v1.ListStreamsResponse.streams:type_name -> infra.loghub.v1.StreamSummary
	13, // 9: infra.loghub.v1.DescribeStreamResponse.stream:type_name -> infra.loghub.v1.StreamConfig
	14, // 10: infra.loghub.v1.StreamConfig.attributes:type_name -> infra.loghub.v1.AttributeSchema
	15, // 11: infra.loghub.v1.StreamConfig.es:type_name -> infra.loghub.v1.ESBackendConfig
	1,  // 12: infra.loghub.v1.LogEvent.AttributesEntry.value:type_name -> infra.loghub.v1.AttributeValue
	1,  // 13: infra.loghub.v1.LogEvent.ResourceEntry.value:type_name -> infra.loghub.v1.AttributeValue
	3,  // 14: infra.loghub.v1.LogHubService.Write:input_type -> infra.loghub.v1.WriteRequest
	5,  // 15: infra.loghub.v1.LogHubService.Bulk:input_type -> infra.loghub.v1.BulkRequest
	8,  // 16: infra.loghub.v1.LogHubService.ListStreams:input_type -> infra.loghub.v1.ListStreamsRequest
	11, // 17: infra.loghub.v1.LogHubService.DescribeStream:input_type -> infra.loghub.v1.DescribeStreamRequest
	4,  // 18: infra.loghub.v1.LogHubService.Write:output_type -> infra.loghub.v1.WriteResponse
	6,  // 19: infra.loghub.v1.LogHubService.Bulk:output_type -> infra.loghub.v1.BulkResponse
	9,  // 20: infra.loghub.v1.LogHubService.ListStreams:output_type -> infra.loghub.v1.ListStreamsResponse
	12, // 21: infra.loghub.v1.LogHubService.DescribeStream:output_type -> infra.loghub.v1.DescribeStreamResponse
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_protocol_protobuf_loghub_loghub_proto_init() }
func file_protocol_protobuf_loghub_loghub_proto_init() {
	if File_protocol_protobuf_loghub_loghub_proto != nil {
		return
	}
	file_protocol_protobuf_loghub_loghub_proto_msgTypes[1].OneofWrappers = []any{
		(*AttributeValue_StringValue)(nil),
		(*AttributeValue_IntValue)(nil),
		(*AttributeValue_DoubleValue)(nil),
		(*AttributeValue_BoolValue)(nil),
		(*AttributeValue_ArrayValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_protobuf_loghub_loghub_proto_rawDesc), len(file_protocol_protobuf_loghub_loghub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_protobuf_loghub_loghub_proto_goTypes,
		DependencyIndexes: file_protocol_protobuf_loghub_loghub_proto_depIdxs,
		MessageInfos:      file_protocol_protobuf_loghub_loghub_proto_msgTypes,
	}.Build()
	File_protocol_protobuf_loghub_loghub_proto = out.File
	file_protocol_protobuf_loghub_loghub_proto_goTypes = nil
	file_protocol_protobuf_loghub_loghub_proto_depIdxs = nil
}
